
export function hpOperationSelect() {
  return {
    hpOperationSelect: {
      0: "EPFU.MODIFYRESOURCES.OPERATIONS.HP.DECREASE",
      1: "EPFU.MODIFYRESOURCES.OPERATIONS.HP.INCREASE",
      2: "EPFU.MODIFYRESOURCES.OPERATIONS.HP.TOMAX",
      3: "EPFU.MODIFYRESOURCES.OPERATIONS.HP.TOZERO",
      4: "EPFU.MODIFYRESOURCES.OPERATIONS.HP.TOCRISIS",
      5: "EPFU.MODIFYRESOURCES.OPERATIONS.HP.TOVALUE"
    }
  }
}

export function mpOperationSelect() {
  return {
    mpOperationSelect: {
      0: "EPFU.MODIFYRESOURCES.OPERATIONS.MP.DECREASE",
      1: "EPFU.MODIFYRESOURCES.OPERATIONS.MP.INCREASE",
      2: "EPFU.MODIFYRESOURCES.OPERATIONS.MP.TOMAX",
      3: "EPFU.MODIFYRESOURCES.OPERATIONS.MP.TOZERO",
      5: "EPFU.MODIFYRESOURCES.OPERATIONS.MP.TOVALUE"
    }
  }
}

export function ipOperationSelect() {
  return {
    ipOperationSelect: {
      0: "EPFU.MODIFYRESOURCES.OPERATIONS.IP.DECREASE",
      1: "EPFU.MODIFYRESOURCES.OPERATIONS.IP.INCREASE",
      2: "EPFU.MODIFYRESOURCES.OPERATIONS.IP.TOMAX",
      3: "EPFU.MODIFYRESOURCES.OPERATIONS.IP.TOZERO",
      5: "EPFU.MODIFYRESOURCES.OPERATIONS.IP.TOVALUE"
    }
  }
}

export function zpOperationSelect() {
  return {
    zpOperationSelect: {
      0: "EPFU.MODIFYRESOURCES.OPERATIONS.ZP.ADVANCE",
      1: "EPFU.MODIFYRESOURCES.OPERATIONS.ZP.CLEAR",
      5: "EPFU.MODIFYRESOURCES.OPERATIONS.ZP.TOVALUE"
    }
  }
}

export function damageTypeSelect() {
  return {
    damageTypeSelect: {
      "physical": "EPFU.MODIFYRESOURCES.DAMAGETYPES.PHYSICAL",
      "air": "EPFU.MODIFYRESOURCES.DAMAGETYPES.AIR",
      "bolt": "EPFU.MODIFYRESOURCES.DAMAGETYPES.BOLT",
      "dark": "EPFU.MODIFYRESOURCES.DAMAGETYPES.DARK",
      "earth": "EPFU.MODIFYRESOURCES.DAMAGETYPES.EARTH",
      "fire": "EPFU.MODIFYRESOURCES.DAMAGETYPES.FIRE",
      "ice": "EPFU.MODIFYRESOURCES.DAMAGETYPES.ICE",
      "light": "EPFU.MODIFYRESOURCES.DAMAGETYPES.LIGHT",
      "poison": "EPFU.MODIFYRESOURCES.DAMAGETYPES.POISON",
      "untyped": "EPFU.MODIFYRESOURCES.DAMAGETYPES.UNTYPED"
    }
  }
}

export function ignoreAffinitiesSelect() {
  return {
    ignoreAffinitiesSelect: {
      0: "EPFU.MODIFYRESOURCES.IGNOREAFFINITIES.NONE",
      1: "EPFU.MODIFYRESOURCES.IGNOREAFFINITIES.RESISTANCES",
      5: "EPFU.MODIFYRESOURCES.IGNOREAFFINITIES.RESISTANCESANDIMMUNITIES",
      15: "EPFU.MODIFYRESOURCES.IGNOREAFFINITIES.ALL"
    }
  }
}
